spring:
  datasource:
    url: jdbc:mysql://${SCAFFOLD_DB_HOST:localhost}:3306/store?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=true&serverTimezone=UTC
    username: ${SCAFFOLD_DB_USER:root}
    password: ${SCAFFOLD_DB_PWD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

