spring:
  datasource:
    username: ${SCAFFOLD_DB_USER:root}
    password: ${SCAFFOLD_DB_PWD:123456}
    url: jdbc:mysql://${SCAFFOLD_DB_HOST:localhost}:3306/store?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=true&serverTimezone=UTC
#    url: jdbc:mysql://${SCAFFOLD_DB_HOST:localhost}:3306/store?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=true&serverTimezone=GMT%2B8
    #url: jdbc:oracle:thin:@${DB_HOST:localhost}:1521/store
    driverClassName: com.mysql.cj.jdbc.Driver   # 以前使用com.mysql.jdbc.Driver
#    driverClassName: com.mysql.jdbc.Driver
#    driverClassName: oracle.jdbc.driver.OracleDriver
    druid:
      initial-size: 1
      max-active: 200
      max-wait: 60000
      min-evictable-idle-time-millis: 300000   # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
      min-idle: 0
      test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接
      test-on-return: false   # 在连接归还到连接池时是否测试该连接
      test-while-idle: true  # 当连接空闲时，是否执行连接测试
      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      validation-query: SELECT 1 FROM DUAL
      filters: config,wall,stat  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      connectionProperties: druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;config.decrypt=false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,*.html,*.htm,*.shtml
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        dialect: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
