spring:
  application:
    name: email-provider
  jpa:  #配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
    hibernate:
      ddl-auto: update

mq:
  kafka:
    bootstrap-server: 192.168.68.128:9092
    retry-count: 2
http:
  connection:
     keepAliveTimeout: 60000


mail:
  default:
      host: XXX.XXX.com
      password: XXX
      username: XXX@XXX.com
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
